# Generated by Django 4.1.7 on 2023-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
        ('selection', '0003_alter_selection_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='items',
        ),
        migrations.AddField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(to='ads.ad'),
        ),
    ]
