# Generated by Django 4.1.7 on 2023-05-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_remove_selection_items_selection_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
