# Generated by Django 4.1.7 on 2023-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
