# Generated by Django 4.1.7 on 2023-03-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADS',
            new_name='AD',
        ),
    ]
